# azure-pipelines.yml
trigger:
- main  # Adjust this to your default branch

pool:
  vmImage: 'ubuntu-latest'  # You can change this to a Windows agent if needed

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'  # Use the Node.js version compatible with your project
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build  # If you have a build step
    npx cypress run --config video=false  # Run tests without video recording
  displayName: 'Install dependencies and run Cypress tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'  # Use appropriate format
    testResultsFiles: '**/test-results.xml'  # Adjust based on your reporter output
    searchFolder: 'cypress/videos'  # Adjust to where your test results are stored
    failOnNoResults: true
    publishRunAttachments: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'cypress/screenshots'  # Publish screenshots if needed
    ArtifactName: 'Screenshots'
    publishLocation: 'Container'
