trigger:
  - main

pool: 'Default'  # Changed to Windows since you're running on Windows

variables:
  baseUrl: 'https://rahulshettyacademy.com/AutomationPractice/'  # Default value from your cypress.config.js

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm ci
  displayName: 'Install Dependencies'

- script: |
    npm install cypress
    npm install @bahmutov/cypress-esbuild-preprocessor
    npm install @badeball/cypress-cucumber-preprocessor
    npm install cypress-mochawesome-reporter
  displayName: 'Install Cypress and Required Packages'

- script: |
    npx cypress verify
  displayName: 'Verify Cypress'

- script: |
    npx cypress run --config baseUrl="$(baseUrl)"
  displayName: 'Run Cypress Tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/cypress/results/*.xml'
    mergeTestResults: true
    testRunTitle: 'Cypress Tests'
  condition: succeededOrFailed()
  displayName: 'Publish Test Results'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)/cypress/videos'
    artifact: 'cypress-videos'
    publishLocation: 'pipeline'
  condition: succeededOrFailed()
  displayName: 'Publish Videos'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)/cypress/screenshots'
    artifact: 'cypress-screenshots'
    publishLocation: 'pipeline'
  condition: failed()
  displayName: 'Publish Screenshots'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)/cypress/reports'
    artifact: 'cypress-reports'
    publishLocation: 'pipeline'
  condition: succeededOrFailed()
  displayName: 'Publish Mochawesome Reports'