trigger:
- main  # Adjust this to your default branch

pool: 'Default'  # You can change this to a Windows agent if needed

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'  # Use the Node.js version compatible with your project
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build  # If you have a build step
    npx cypress run --config video=false --reporter junit --reporter-options 'mochaFile=results/test-results-[hash].xml'
  displayName: 'Run Cypress tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'  # Use appropriate format
    testResultsFiles: '**/results/test-results-*.xml'  # Ensure this matches your output
    searchFolder: 'results'  # Adjust to where your test results are stored
    failOnNoResults: true
    publishRunAttachments: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'cypress/screenshots'  # Publish screenshots if needed
    ArtifactName: 'Screenshots'
    publishLocation: 'Container'
