# azure-pipelines.yml

trigger:
- main  # Adjust this to your default branch

pool: 'Default'  # Use a Windows agent if needed

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'  # Use the Node.js version compatible with your project
  displayName: 'Install Node.js'

- script: |
    node -v  # Log Node.js version
    npm -v   # Log npm version
  displayName: 'Check Node and NPM versions'

- script: npm install  # Ensure dependencies are installed correctly
  displayName: 'Install dependencies'

- script: |
    npm run build  # Optional: If you have a build step
  displayName: 'Build Project'

- script: |
    npx cypress run --config video=true --reporter mochawesome --reporter-options 'reportDir=cypress/reports,overwrite=true,html=true,json=true'
  displayName: 'Run Cypress tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'  # Use JUnit format for test results
    testResultsFiles: '**/cypress/reports/*.json'  # Adjust to match your mochawesome output
    searchFolder: 'cypress/reports'  # Folder where your test results are stored
    failOnNoResults: true  # Fail the build if no test results are found
    publishRunAttachments: true  # Publish attachments such as screenshots and videos

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'cypress/screenshots'  # Publish screenshots if needed
    ArtifactName: 'Screenshots'  # Name of the artifact
    publishLocation: 'Container'  # Publish location

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'cypress/videos'  # Publish videos if needed
    ArtifactName: 'Videos'  # Name of the artifact
    publishLocation: 'Container'  # Publish location
